### ISSUE TITLE
XON / XOFF 是软件流控制。

### ISSUE THREAD

**Issue by YuanXiaoQing666** [ericawes/azure-sphere-issues#275]
[UART_FlowControl_XONXOFF
启用 XON / XOFF 软件流控制。原文写的是硬件流]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d447d055-ba8b-4134-c172-8c8dff56a4db
* Version Independent ID: 9f094a7a-bccf-5fd6-7f15-af888d45264a
* Content: [UART_FlowControl 枚举 - Azure Sphere](https://docs.microsoft.com/zh-cn/azure-sphere/reference/applibs-reference/applibs-uart/enum-uart-flowcontrol)
* Content Source: [AzureSphere/articles/reference/applibs-reference/applibs-uart/enum-uart-flowcontrol.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr.zh-CN/blob/live/AzureSphere/articles/reference/applibs-reference/applibs-uart/enum-uart-flowcontrol.md)
* Product: **azure-sphere**
* GitHub Login: @esalc
* Microsoft Alias: **azurespheredocs**

**Comment by BharathNimmala-MSFT** [comment]
@YuanXiaoQing666 Thank you for reaching out with your query, our team will review it and get back to you.

**Comment by asergaz** [comment]
@YuanXiaoQing666 could you please rephrase your question in English? Let me know if you are recommending an enhancement to the doc so I assign to the author? Thanks!

fyi @esalc

**Comment by YuanXiaoQing666** [comment]
Caused by incorrect translation.&nbsp;
Read in English，XON/XOFF is&nbsp;software flow control. But translate&nbsp;in Chinese,&nbsp; it's same to&nbsp;RTS/CTS, show the hardware flow control.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MicrosoftDocs/azure-sphere-issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MicrosoftDocs/azure-sphere-issues] XON / XOFF 是软件流控制。 (#275)





 
@YuanXiaoQing666 could you please rephrase your question in English? Let me know if you are recommending an enhancement to the doc so I assign to the author? Thanks!
 
fyi @esalc

**Comment by asergaz** [comment]
Thank you for the clarification @YuanXiaoQing666 ! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by ericawes** [comment]
I believe this translation has been corrected; closing the ticket.
