### ISSUE TITLE
Coding for renewable security link is broken

### ISSUE THREAD

**Issue by xiongyu0523** [ericawes/azure-sphere-issues#282]
[Enter feedback here]

Coding for renewable security link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0893c5f5-fd90-8aae-f6ae-62917288b7c2
* Version Independent ID: 77422ee2-84c7-03d6-72e9-85491831347f
* Content: [What's new - Azure Sphere](https://docs.microsoft.com/en-us/azure-sphere/product-overview/whats-new)
* Content Source: [AzureSphere/articles/product-overview/whats-new.md](https://github.com/MicrosoftDocs/Azure-Sphere-Docs-pr/blob/live/AzureSphere/articles/product-overview/whats-new.md)
* Product: **azure-sphere**
* GitHub Login: @ericawes
* Microsoft Alias: **azurespheredocs**

**Comment by ericawes** [comment]
Thank you for letting me know, @xiongyu0523! The other links in that table were broken as well; I've just fixed them.
